### ISSUE TITLE
Quotes within article titles cause problems with the git command

### ISSUE THREAD

**Issue by w4tsn** [peterjc/mediawiki_to_git_md#28]
The process gets stuck/killed by a git-error when the converter has to deal with articles which contain quotation with their titles. The converter creates the files as expected, but the git command exits with an error.

I worked around this issue by:

1. create a copy of the generated `.md` and `.mediawiki` files
2. issue `git add wiki/ && git commit -m "fix quotation"`

**Comment by peterjc** [comment]
I remember having to deal with quoted in the commit message.

I would guess this would fix it, where I deal with spaces in filenames by quoting them:

https://github.com/peterjc/mediawiki_to_git_md/blob/1ad6868c21e8f10a72574326682345495b6a899b/convert.py#L375

Try replacing:

```python
    cmd = '"%s" add "%s"' % (git, '" "'.join(filenames))
```

with:

```python
   cmd = '"%s" add "%s"' % (git, '" "'.join(filenames.replace('"', '\"')))
```

i.e. Let's try slash escaping any double quotes within filenames.

However, probably a better idea would be to extend function ``make_filename`` to replace the quotes with an underscore in the local filenames:

https://github.com/peterjc/mediawiki_to_git_md/blob/1ad6868c21e8f10a72574326682345495b6a899b/convert.py#L259

```python
    return os.path.join(prefix, title.replace(" ", "_").replace(":", "_").replace("/", "_") + os.path.extsep + ext)
```

replace with:

```python
    return os.path.join(prefix, title.replace(" ", "_").replace(":", "_").replace("/", "_").replace('"', "_") + os.path.extsep + ext)
```

Are you able to test these ideas, or are you done with your migration?

**Comment by w4tsn** [comment]
I'm done with the migration already, but I still have the problematic dumb laying around. I'll give it a try this weekend.
