### ISSUE TITLE
Wish:   mediawiki_export.xml  in this git repo

### ISSUE THREAD

**Issue by stappersg** [peterjc/mediawiki_to_git_md#38]
Hi,

My attempts to convert a mediawiki XML export to git repository failed. (Most likely due an ancient mediawiki engine at my side.)

I think it would be a good thing, if this git repository contains a _known good mediawiki XML export_.  Good for this project for having a reference XML, good for new users like me for having a _"See, it works!"_.

Please add a  `mediawiki_export.xml` to this git repository.

Groeten
Geert Stappers

**Comment by peterjc** [comment]
In the short term, there was some discussion of examples from Wikipedia (the size varies dramatically by language) on this issue tracker.

In the medium term, I think I have some real world examples on my desktop computer but am currently away. I'll be home next week so feel free to remind me if I don't reply.

**Comment by stappersg** [comment]
The requested reminder on

> I think I have some real world examples on my desktop computer

**Comment by peterjc** [comment]
I still have MediaWiki dumps from 1 Jan 2024 (on my desktop from issue #29) for cywiki, tawiki, and wawiki - but they are too big for attaching to a GitHub issue (and require converting from .bz2 to .zip which doubles their size).

I also have the OBF MediaWiki dump of 5 Feb 2024 as used for https://github.com/OBF/wiki which we've been considering sharing somewhere public anyway. That's 127MB as bz2, 137MB as zip. In the short term I'll put this up on my personal DropBox account:

https://www.dropbox.com/s/edp7ukdhg2onls7/obf_mediawiki_dump_2024-02-05.xml.bz2?dl=0
